### ISSUE TITLE
Is parent_space_group too much of a namespace landgrab?

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/magnetic_dic#14]
The category "parent_space_group" sounds rather broad. Are we sure that no other crystallographic areas need this, or that the definitions are general enough to cover them?

**Comment by jamesrhester** [comment]
parent_magnetic_propagation_vector is in a similar boat. Prefer magnetic_propagation_vector_parent.

**Comment by jamesrhester** [comment]
Branton advises leaving as is.  I would still prefer magnetic_propagation_vector_parent.

**Comment by brantonc** [comment]
A (sometimes non-unique) parent space group can be defined for any crystal structure that can be idealized into a higher symmetry form.  While broad, the category is perfectly appropriate and not likely to collide with other crystallographic namespaces.  Upon defining a parent space group, there will always be one or more propagation vectors that relate the parent and child lattices; depending on the situation, a specific propagation vector could be associated with magnetic or non-magnetic order parameters or both.  I suggest that we simply drop the word "magnetic" from the tag name.

**Comment by jamesrhester** [comment]
Agreed. Edited out 'magnetic' from magnetic_propagation_vector_parent

**Comment by brantonc** [comment]
Also, I strongly recommend keeping _parent as the category prefix since _parent_space_group and _parent_propagation_vector are just the first two (and most essential) tags among many likely to be defined for the description of the parent of a given crystal structure.

**Comment by jamesrhester** [comment]
Understood. parent_propagation_vector and parent_space_group will remain as is.
