### ISSUE TITLE
Ca we have fractions in a DDLm vector?

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/magnetic_dic#15]
Draft definition for kxkykz wants a rational fraction, but vectors in DDLm are usually Real or Integer. Can we create a Rational type?

**Comment by brantonc** [comment]
A rational type would be nice since only rational values are permitted.  But if push comes to shove, we can represent a rational value with a real (decimal) value.

**Comment by jamesrhester** [comment]
I will leave as is but raise the issue of an additional Rational type with the DDLm group.
