### ISSUE TITLE
Can we use proper DDLm matrices for the transformations?

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/magnetic_dic#18]
The transform_Pp_abc datanames could be represented as proper DDLm matrices

**Comment by jamesrhester** [comment]
Definitions added of form 'transform_P'. Fully fleshed out _space_group.magn_transform_BNS_P for Branton to vet.

**Comment by brantonc** [comment]
Consider 'transform_Pp_mat' instead.  The small 'p' is needed since the origin shift is included in the matrix, and the 'mat' is needed to differentiate the name from 'abc'.

**Comment by brantonc** [comment]
As I look at the structure of the dictionary and the new Matrix quantities that have been added recently, it makes good sense to leave off the 'mat' from the names.

**Comment by jamesrhester** [comment]
OK, I will update the dictionary to remove 'Mat' - I agree that it is unnecessary.
