### ISSUE TITLE
transformloop descriptions should be just free text, not fixed strings

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/magnetic_dic#19]
The descriptions seem to want to be both fixed strings, and free text.  Suggest fixing the possible strings, and other tabulations can then be added to the dictionary as they become available.

**Comment by jamesrhester** [comment]
Created _space_group_magn_ssg_transforms.source with enumerated strings, although Branton suggests only free text is reasonable.

**Comment by brantonc** [comment]
That's fine so long as free text is possible for undefined settings such as literature references.

**Comment by jamesrhester** [comment]
Added "source" enumerated types for _space_group_magn_transforms as well, and adjusted definitions accordingly.
