### ISSUE TITLE
atom_site_moment category

### ISSUE THREAD

**Issue by brantonc** [COMCIFS/magnetic_dic#21]
Based on the other category entries in the dictionary, it seems that the _name.category_id of _atom_site_moment category should be MAGNETIC.  Or is this a quirk of being a child category?

**Comment by jamesrhester** [comment]
Yes, because _atom_site_moment is a child of something in the core dictionary, its parent is the _atom_site category. The MAGNETIC category acts as the parent category for those categories that are not children of any other category.
