### ISSUE TITLE
Rename the default branch from 'master' to 'main

### ISSUE THREAD

**Issue by vaitkus** [COMCIFS/magnetic_dic#29]
This potential reasons for renaming the branch are provide in issue https://github.com/COMCIFS/comcifs.github.io/issues/11.

The renaming should happen after the majority of the outstanding PRs are merged. I suggest a period of two weeks for anyone to raise their concerns after which the renaming can be carried out given that all of the relevant PRs are merged. Are there any objections to this proposal?

**Comment by brantonc** [comment]
I have no objection.  If such a change is still needed, please do it now before we introduce a series of new commits.

**Comment by vaitkus** [comment]
@jamesrhester , could you please do the renaming? I don't have sufficient permissions to do that.

**Comment by jamesrhester** [comment]
Done
