### ISSUE TITLE
Annotate magn_name_BNS and magn_point_group examples

### ISSUE THREAD

**Issue by jamesrhester** [COMCIFS/magnetic_dic#8]
The examples of BNS names in magn_name_BNS, mag_name_OG, and mag_point_group names would be improved by adding _description_example.detail describing briefly how the names are interpreted.

**Comment by jamesrhester** [comment]
After discussion with Branton we decided that Branton would consider some short text and ask D. Litvin for the corresponding text for OG equivalents.

**Comment by brantonc** [comment]
I don't completely understand the implications of a "detail" section.  But it seems that you want it to be specific enough for generating operator matrices from the symbols provided.  I very strongly recommend not pursuing this rather controversial issue right now.  At present, the Commission on Magnetic Structures only agree that the symbols reliably point to MSG entries in the ISOMAG and Litvin tables.
